(function(){
const base=JSON.parse(JSON.stringify(window.HOLLOW_DOMINION_DATA));let data=JSON.parse(JSON.stringify(base));const $=s=>document.querySelector(s),fmt=(n,d=1)=>Number(n).toLocaleString('fr-FR',{maximumFractionDigits:d}),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function listAffixes(item){return[...(item.implicits||[]),...(item.prefixes||[]),...(item.suffixes||[])];}
function gearCard(item){const aff=listAffixes(item).map(a=>`<li class="${a.status||''}${a.active===false?' inactive':''}">${esc(a.label)}${a.active===false?' <em>(hors calcul)</em>':''}</li>`).join('');const unique=(item.unique||[]).map(x=>`<li>${esc(x)}</li>`).join('');const d=HD_CALC.calcItemDefences(item,data),def=item.defenceBase?`<p class="gearComputed">Qualité ${fmt(item.quality,0)}% · ${fmt(d.evasion,0)} Eva · ${fmt(d.energyShield,0)} ES local</p>`:'';return`<article><div class="icon">${esc(item.name.slice(0,2))}</div><h3>${esc(item.name)}</h3><small>${esc(item.slot)} · ${esc(item.rarity)}</small>${def}${aff?`<ul>${aff}</ul>`:''}${unique?`<ul>${unique}</ul>`:''}</article>`;}
function skillCard(s){return`<article><div class="icon skillIcon">${esc(s.name.slice(0,2))}</div><h3>${esc(s.name)}</h3><small>${esc(s.role)}</small><ol>${s.supports.map(x=>`<li>${esc(x)}</li>`).join('')}</ol></article>`;}
function kv(rows){return rows.map(([a,b])=>`<div><span>${esc(a)}</span><strong>${b}</strong></div>`).join('');}
function render(){
$('#gear').innerHTML=Object.values(data.gear).map(gearCard).join('');$('#skills').innerHTML=data.skills.map(skillCard).join('');const s=HD_CALC.calcAll(data),r=s.resistances,cr=s.crit,sp=s.spirit;
$('#character').innerHTML=kv([['Vie',fmt(s.resources.life,0)],['Mana',fmt(s.resources.mana,0)],['ES',fmt(s.defences.energyShield,0)],['Évasion',fmt(s.defences.evasion,0)],['Deflection',fmt(s.defences.deflection,0)],['Évasion — Shimmering',fmt(s.defences.evasionShimmering,0)],['Deflection — Shimmering',fmt(s.defences.deflectionShimmering,0)],['Déplacement',`+${fmt(s.movement.permanent,0)}% / +${fmt(s.movement.whileEnergyShield,0)}% avec ES`],['Force',fmt(s.attributes.strength,0)],['Dextérité',fmt(s.attributes.dexterity,0)],['Intelligence',fmt(s.attributes.intelligence,0)],['Attack Speed',`${fmt(s.attackSpeed.min,2)} – ${fmt(s.attackSpeed.max,2)} APS`],['Mana regen + Clarity',`${fmt(s.manaRegen.withClarity,1)}/s`],['Mana regen + Shock récent',`${fmt(s.manaRegen.withClarityAndRecentShock,1)}/s`],['Runic Ward',fmt(s.runicWard,0)],['Crit Dmg Bonus',`+${fmt(cr.critDamageBonus,0)}%`]]);
const names={fire:'Feu',cold:'Froid',lightning:'Foudre',chaos:'Chaos'};$('#res').innerHTML=Object.keys(names).map(k=>{const p=r.afterPenalty[k],cls=p<75?'low':p>77?'over':'perfect';return`<div class="resRow ${cls}"><span>${names[k]}</span><strong>${fmt(Math.min(75,p),1)}%</strong><small>avant cap ${fmt(p,1)}%</small></div>`;}).join('');
$('#crit').innerHTML=kv([['Base arme',`${fmt(cr.baseWeapon,1)}%`],['Increased total',`${fmt(cr.increased,1)}%`],['Permanent',`${fmt(cr.permanent,2)}%`],['Cible Dazed',`${fmt(cr.vsDazed,2)}%`],['CDB',`+${fmt(cr.critDamageBonus,0)}%`],['CDB après Power Charge',`+${fmt(cr.critDamageAfterPowerCharge,0)}%`]]);$('#spirit').innerHTML=kv([['Total',fmt(sp.total,0)],['Réservé',fmt(sp.reserved,0)],['Libre',fmt(sp.free,0)]]);$('#damage').innerHTML=kv(data.skillDamageSnapshot.entries.map(([n,a,b])=>[n,`${fmt(a,0)} – ${fmt(b,0)}`]));$('#priorities').innerHTML=data.priorities.map(p=>`<li><b>#${p.id} ${esc(p.title)}</b> <span>${esc(p.status)}</span><small>${esc(p.note)}</small></li>`).join('');renderEditor();}
function setPath(obj,path,val){const parts=path.split('.'),last=parts.pop(),target=parts.reduce((o,k)=>o[k],obj);target[last]=val;}
function input(label,path,value,step='1'){return`<label><span>${esc(label)}</span><input type="number" step="${step}" data-path="${esc(path)}" value="${value}"></label>`;}
function checkbox(label,path,value){return`<label><span>${esc(label)}</span><input type="checkbox" data-path="${esc(path)}" ${value?'checked':''}></label>`;}
function itemEditor(key,item){let html=`<div class="editorItem"><h3>${esc(item.name)}</h3>`;if(item.quality!==undefined)html+=input('Qualité %',`gear.${key}.quality`,item.quality);if(item.defenceBase){html+=input('Base Evasion',`gear.${key}.defenceBase.evasion`,item.defenceBase.evasion)+input('Base ES',`gear.${key}.defenceBase.energyShield`,item.defenceBase.energyShield);}if(key==='gloves'){html+=input('Attack Speed min %',`gear.${key}.attackSpeedPctMin`,item.attackSpeedPctMin)+input('Attack Speed max %',`gear.${key}.attackSpeedPctMax`,item.attackSpeedPctMax);}if(key==='weapon'){html+=input('Base APS',`gear.${key}.baseAttackSpeed`,item.baseAttackSpeed,'.01')+input('Base crit %',`gear.${key}.baseCritPct`,item.baseCritPct,'.1')+input('Attack Speed local %',`gear.${key}.localAttackSpeedPct`,item.localAttackSpeedPct)+input('CDB %',`gear.${key}.critDamageBonusPct`,item.critDamageBonusPct)+input('Runic Ward',`gear.${key}.runicWard`,item.runicWard);}if(key==='belt'){html+=input('Bonus bague gauche %',`gear.${key}.ringBonusLeftPct`,item.ringBonusLeftPct)+input('Bonus bague droite %',`gear.${key}.ringBonusRightPct`,item.ringBonusRightPct);}listAffixes(item).forEach(a=>{if(!a.stat)return;const group=(item.implicits||[]).includes(a)?'implicits':(item.prefixes||[]).includes(a)?'prefixes':'suffixes';const realIdx=(item[group]||[]).indexOf(a),path=`gear.${key}.${group}.${realIdx}`;if(a.active!==undefined)html+=checkbox(`Compter : ${a.label}`,`${path}.active`,a.active);html+=input(a.label,`${path}.value`,a.value,'.1');});return html+'</div>';}
function renderEditor(){let html='<p class="editorNotice"><b>Phase actuelle :</b> seul l’équipement est modifiable. L’arbre et les bonus permanents de campagne sont verrouillés comme constantes de calcul jusqu’à leur intégration interactive.</p>';Object.entries(data.gear).forEach(([key,item])=>html+=itemEditor(key,item));html+='<p>Les suffixes libres du casque et de l’amulette restent volontairement vierges. Le +30% Attack Speed de la Topaze reste hors calcul tant que son audit n’est pas validé.</p>';$('#editorFields').innerHTML=html;$('#editorFields').querySelectorAll('input').forEach(i=>{i.oninput=()=>{const v=i.type==='checkbox'?i.checked:Number(i.value);setPath(data,i.dataset.path,v);localStorage.setItem('hd-live',JSON.stringify(data));render();};});}
try{const saved=localStorage.getItem('hd-live');if(saved){const parsed=JSON.parse(saved);if(parsed?.meta?.stateVersion===base.meta.stateVersion)data=parsed;else localStorage.removeItem('hd-live');}}catch(e){localStorage.removeItem('hd-live');}
$('#editBtn').onclick=()=>document.body.classList.toggle('open');$('#resetBtn').onclick=()=>{data=JSON.parse(JSON.stringify(base));localStorage.removeItem('hd-live');render();};$('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='HOLLOW_DOMINION_live_state.json';a.click();URL.revokeObjectURL(a.href);};render();
})();