(function(){
const base=JSON.parse(JSON.stringify(window.HOLLOW_DOMINION_DATA));let data=JSON.parse(JSON.stringify(base));const $=s=>document.querySelector(s),fmt=(n,d=1)=>Number(n).toLocaleString('fr-FR',{maximumFractionDigits:d}),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function listAffixes(item){return[...(item.implicits||[]),...(item.prefixes||[]),...(item.suffixes||[])];}
function gearCard(item){const aff=listAffixes(item).map(a=>`<li class="${a.status||''}">${esc(a.label)}</li>`).join('');const unique=(item.unique||[]).map(x=>`<li>${esc(x)}</li>`).join('');return`<article><div class="icon">${esc(item.name.slice(0,2))}</div><h3>${esc(item.name)}</h3><small>${esc(item.slot)} · ${esc(item.rarity)}</small>${aff?`<ul>${aff}</ul>`:''}${unique?`<ul>${unique}</ul>`:''}</article>`;}
function skillCard(s){return`<article><div class="icon skillIcon">${esc(s.name.slice(0,2))}</div><h3>${esc(s.name)}</h3><small>${esc(s.role)}</small><ol>${s.supports.map(x=>`<li>${esc(x)}</li>`).join('')}</ol></article>`;}
function kv(rows){return rows.map(([a,b])=>`<div><span>${esc(a)}</span><strong>${b}</strong></div>`).join('');}
function render(){
$('#gear').innerHTML=Object.values(data.gear).map(gearCard).join('');$('#skills').innerHTML=data.skills.map(skillCard).join('');const c=data.workingCharacter,r=HD_CALC.calcResistances(data),cr=HD_CALC.calcCrit(data),sp=HD_CALC.calcSpirit(data);
$('#character').innerHTML=kv([['Vie',fmt(c.life,0)],['Mana',fmt(c.mana,0)],['ES',fmt(c.energyShield,0)],['Évasion',fmt(c.evasion,0)],['Deflection',fmt(c.deflection,0)],['Déplacement',`+${fmt(c.movementSpeedPct,0)}%`],['Force',fmt(c.strength,0)],['Dextérité',fmt(c.dexterity,0)],['Intelligence',fmt(c.intelligence,0)],['Attack Speed',fmt(c.attackSpeed,2)],['Mana regen',`${fmt(c.manaRegenPerSecond,0)}/s`],['Crit Dmg Bonus',`+${fmt(c.critDamageBonusPct,0)}%`]]);
const names={fire:'Feu',cold:'Froid',lightning:'Foudre',chaos:'Chaos'};$('#res').innerHTML=Object.keys(names).map(k=>{const p=r.afterPenalty[k],cls=p<75?'low':p>77?'over':'perfect';return`<div class="resRow ${cls}"><span>${names[k]}</span><strong>${fmt(Math.min(75,p),1)}%</strong><small>avant cap ${fmt(p,1)}%</small></div>`;}).join('');
$('#crit').innerHTML=kv([['Base arme',`${fmt(c.crit.weaponBasePct,1)}%`],['Increased total',`${fmt(cr.increased,1)}%`],['Permanent',`${fmt(cr.permanent,2)}%`],['+ Power Charge',`${fmt(cr.powerCharge,2)}%`],['+ cible Blind',`${fmt(cr.blindBoss,2)}%`]]);$('#spirit').innerHTML=kv([['Total',fmt(sp.total,0)],['Réservé',fmt(sp.reserved,0)],['Libre',fmt(sp.free,0)]]);$('#damage').innerHTML=kv(data.skillDamageSnapshot.entries.map(([n,a,b])=>[n,`${fmt(a,0)} – ${fmt(b,0)}`]));$('#priorities').innerHTML=data.priorities.map(p=>`<li><b>#${p.id} ${esc(p.title)}</b> <span>${esc(p.status)}</span><small>${esc(p.note)}</small></li>`).join('');renderEditor();}
function setPath(obj,path,val){const parts=path.split('.'),last=parts.pop(),target=parts.reduce((o,k)=>o[k],obj);target[last]=val;}
function input(label,path,value,step='1'){return`<label><span>${esc(label)}</span><input type="number" step="${step}" data-path="${esc(path)}" value="${value}"></label>`;}
function renderEditor(){const c=data.workingCharacter,rr=data.rules;$('#editorFields').innerHTML=`<h3>Critique</h3>${input('Base crit arme','workingCharacter.crit.weaponBasePct',c.crit.weaponBasePct,'.1')}${input('Increased crit gear','workingCharacter.crit.increasedPctFromGear',c.crit.increasedPctFromGear)}${input('Increased crit jewels','workingCharacter.crit.increasedPctFromJewels',c.crit.increasedPctFromJewels)}<h3>Ingéniosité</h3>${input('Bague gauche %','rules.ingenuityLeftRingBonusPct',rr.ingenuityLeftRingBonusPct)}${input('Bague droite %','rules.ingenuityRightRingBonusPct',rr.ingenuityRightRingBonusPct)}<h3>Spirit / Mana</h3>${input('Spirit total','workingCharacter.spiritTotal',c.spiritTotal)}${input('Spirit réservé','workingCharacter.spiritReserved',c.spiritReserved)}${input('Mana','workingCharacter.mana',c.mana)}${input('Mana regen/s','workingCharacter.manaRegenPerSecond',c.manaRegenPerSecond)}<p>Les deux suffixes libres (casque + amulette) restent volontairement vierges dans build-data.js.</p>`;$('#editorFields').querySelectorAll('input').forEach(i=>i.oninput=()=>{setPath(data,i.dataset.path,Number(i.value));localStorage.setItem('hd-live',JSON.stringify(data));render();});}
try{const saved=localStorage.getItem('hd-live');if(saved)data=JSON.parse(saved);}catch(e){}
$('#editBtn').onclick=()=>document.body.classList.toggle('open');$('#resetBtn').onclick=()=>{data=JSON.parse(JSON.stringify(base));localStorage.removeItem('hd-live');render();};$('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='HOLLOW_DOMINION_live_state.json';a.click();URL.revokeObjectURL(a.href);};render();
})();