window.HOLLOW_DOMINION_DATA={
meta:{name:"HOLLOW DOMINION",author:"Nejib",gameVersion:"0.5.2",className:"Monk",ascendancy:"Martial Artist",passiveTree:"Default 120 + 8",referenceImage:"ChatGPT Image 9 sept. 2026, 05_47_28(1).png",stateVersion:"live-1.1-equipment",updated:"2026-09-09",note:"Phase équipement interactive : l'arbre et les bonus permanents de campagne sont utilisés comme sources verrouillées de calcul, mais seul l'équipement est modifiable dans le live build pour le moment."},
rules:{endgameElementalPenalty:-60,endgameChaosPenalty:0,resistanceCap:75,ingenuityRounding:"floor-per-mod",qualityLocalDefenceMorePerPct:1},
referenceSnapshot:{life:1642,mana:1218,energyShield:6487,evasion:18245,deflection:8020,movementSpeedPct:37,strength:95,dexterity:195,intelligence:95,critChancePct:62,critDamageBonusPct:275,attackSpeed:2.48,manaRegenPerSecond:312,spiritTotal:245,spiritReserved:207,resistancesDisplayed:{fire:75,cold:75,lightning:75,chaos:75}},
fixedSources:{
status:{tree:"locked-summary / UI à intégrer plus tard",campaign:"locked-summary / UI à intégrer plus tard",editableSource:"equipment-only"},
character:{level:100,baseStrength:7,baseDexterity:11,baseIntelligence:11,baseLife:28,lifePerLevel:12,baseMana:34,manaPerLevel:4,baseEvasion:7,baseManaRegenPctPerSecond:4,baseCritDamageBonusPct:100},
tree:{fixedAttributes:{strength:10,dexterity:35,intelligence:10},flexibleAttributes:{strength:20,dexterity:20,intelligence:50,nodes:18,note:"Répartition de travail : 4 STR / 4 DEX / 10 INT ; à remplacer par les choix sérialisés quand l'arbre interactif sera intégré."},increasedEnergyShieldPct:179,increasedEvasionPct:179,evasionAsDeflectionPct:33,evasionIfNotHitRecentlyPct:20,spectralWardBodyEvasionDivisor:12,esRechargeStartFasterPct:40,esRechargeStartFasterIfNotFullLifePct:20,manaRegenPct:48,resistances:{fire:5,cold:5,lightning:5,chaos:5},movementSpeedPct:4,movementSpeedWhileEnergyShieldPct:3,skillSpeedPct:19,attackCastSpeedPct:8,quarterstaffAttackSpeedPct:6,critChanceIncreasedPct:-10,critChanceVsDazedIncreasedPct:25,critDamageBonusPct:115,critDamageBonusAfterPowerChargePct:60},
campaign:{attributes:{strength:5,dexterity:5,intelligence:5},flatLife:20,maxLifePct:5,maxManaPct:5,spirit:100,manaRegenPct:25,kaomDefencesPct:30,resistances:{fire:15,cold:15,lightning:15,chaos:0},ancientVowsCharmChargesGainedPct:30,manaRecoveryFromFlasksPct:30,note:"Résistances = +10% fixes de campagne + Tabana +5%. Kaom = +30% Armour/Evasion/ES."},
skills:{spiritReserved:197,clarityManaRegenPct:50,recentShockManaRegenPct:25,vitalityLifeRegenPct:2}
},
gear:{
helmet:{slot:"Casque",name:"Masque souriant",rarity:"Rare BiS — travail",quality:20,defenceBase:{evasion:187,energyShield:57},prefixes:[{label:"+120 maximum ES",value:120,stat:"localFlatES"},{label:"+140% Évasion et ES",value:140,stat:"localEvasionESPct"},{label:"+90 Mana maximal",value:90,stat:"maxMana"}],suffixes:[{label:"+45 Dextérité",value:45,stat:"dexterity"},{label:"+40% Résistance feu",value:40,stat:"resFire"},{label:"Suffixe libre — à optimiser",value:0,stat:null,status:"free"}]},
gloves:{slot:"Gants",name:"Caresse de Lochton → Poings de pierre",rarity:"Unique / Way of the Stonefist",quality:20,defenceBase:{evasion:400,energyShield:200},attackSpeedPctMin:13,attackSpeedPctMax:20,unique:["Interaction Stonefist obligatoire","Défenses de travail niv.100 avant qualité : 400 Evasion / 200 ES","Attack Speed : 13–20% selon le roll — valeur exacte à verrouiller","Cannot Leech Mana après transformation","Génération/partage de charges"]},
weapon:{slot:"Arme",name:"Duality",rarity:"Unique — Runemastered Warding Quarterstaff",baseAttackSpeed:1.4,baseCritPct:10,localAttackSpeedPct:22,critDamageBonusPct:30,runicWard:50,physicalDamagePct:300,unique:["+50 maximum Runic Ward","+300% increased Physical Damage","+30% Critical Damage Bonus","+22% increased Attack Speed local","Variante 10% crit actuelle ; variante 15% à comparer"]},
chest:{slot:"Armure",name:"Veste racée",rarity:"Rare BiS — travail",quality:20,defenceBase:{evasion:285,energyShield:87},baseMovementSpeedPct:-3,prefixes:[{label:"+180 maximum ES",value:180,stat:"localFlatES"},{label:"+160% Évasion et ES",value:160,stat:"localEvasionESPct"},{label:"+61 Spirit",value:61,stat:"spirit"}],suffixes:[{label:"+40% Résistance feu",value:40,stat:"resFire"},{label:"+40% Résistance froid",value:40,stat:"resCold"},{label:"+41% Résistance foudre",value:41,stat:"resLightning"}]},
belt:{slot:"Ceinture",name:"Ingéniosité",rarity:"Unique",ringBonusLeftPct:30,ringBonusRightPct:30,unique:["Objectif BiS : +30% bonus bague gauche","Objectif BiS : +30% bonus bague droite","1–3 emplacements de Charme"]},
boots:{slot:"Bottes",name:"Chaussures à dague",rarity:"Rare BiS — travail",quality:20,defenceBase:{evasion:140,energyShield:43},prefixes:[{label:"+95 maximum ES",value:95,stat:"localFlatES"},{label:"+140% Évasion et ES",value:140,stat:"localEvasionESPct"},{label:"+35% Vitesse de déplacement",value:35,stat:"moveSpeedPct"}],suffixes:[{label:"+40% Résistance feu",value:40,stat:"resFire"},{label:"+40% Résistance froid",value:40,stat:"resCold"},{label:"+40% Résistance foudre",value:40,stat:"resLightning"}]},
amulet:{slot:"Amulette",name:"Amulette solaire",rarity:"Rare BiS — travail",implicits:[{label:"+15 Spirit",value:15,stat:"spirit"}],prefixes:[{label:"+50 Spirit",value:50,stat:"spirit"},{label:"+74 Mana maximal",value:74,stat:"maxMana"},{label:"+40 maximum ES",value:40,stat:"maxES"}],suffixes:[{label:"+3 niveau de toutes les Aptitudes de Mêlée",value:3,stat:"meleeSkillLevels"},{label:"+40% Résistance froid",value:40,stat:"resCold"},{label:"Suffixe libre — à optimiser",value:0,stat:null,status:"free"}]},
ringAmethyst:{slot:"Bague gauche",name:"Bague d'Améthyste",rarity:"Rare BiS — travail",ingenuitySide:"left",implicits:[{label:"+13% Résistance chaos",value:13,stat:"resChaos",ingenuity:true}],prefixes:[{label:"+85 maximum ES",value:85,stat:"maxES",ingenuity:true},{label:"+35 Mana maximal",value:35,stat:"maxMana",ingenuity:true},{label:"+15 Dextérité",value:15,stat:"dexterity",ingenuity:true}],suffixes:[{label:"+45% Dégâts de froid",value:45,stat:"coldDamagePct",ingenuity:true},{label:"+35% Bonus de Dégâts critiques",value:35,stat:"critDamageBonusPct",ingenuity:true},{label:"+20% Résistance chaos",value:20,stat:"resChaos",ingenuity:true}]},
ringTopaz:{slot:"Bague droite",name:"Bague de Topaze",rarity:"Rare BiS — travail",ingenuitySide:"right",implicits:[{label:"+30% Résistance foudre",value:30,stat:"resLightning",ingenuity:true}],prefixes:[{label:"+90 maximum ES",value:90,stat:"maxES",ingenuity:true},{label:"+33 Force",value:33,stat:"strength",ingenuity:true},{label:"+30% Vitesse d'attaque",value:30,stat:"attackSpeedPct",ingenuity:true,status:"audit",active:false}],suffixes:[{label:"+21% Résistance chaos",value:21,stat:"resChaos",ingenuity:true},{label:"Suffixe à définir",value:0,stat:null,status:"open"},{label:"Suffixe à définir",value:0,stat:null,status:"open"}]}
},
skills:[
{name:"Hollow Form → Whirling Assault",role:"Main DPS boss",supports:["Heavy Swing","Heightened Charges","Blindside","Vorana's Siege"]},
{name:"Shattering Palm",role:"Clear / Freeze",supports:["Ancestral Call II","Rapid Attacks II","Magnified Area II","Elemental Armament II","Rising Tempest"]},
{name:"Charged Staff",role:"Lightning / Shock / Blind",supports:["Blind II","Perpetual Charge","Prolonged Duration II","Elemental Armament II","Innervate"]},
{name:"Tempest Bell",role:"Burst / Elemental",supports:["Heavy Swing","Close Combat II","Ancestral Call II","Overabundance II","Rage III"]},
{name:"Hollow Resonance",role:"Stun",supports:["Stun III","Cooldown Recovery II","Close Combat II","Magnified Area II","Pinpoint Critical"]},
{name:"Hollow Focus",role:"Heavy Stun",supports:["Cooldown Recovery II","Overabundance II","Magnified Area II","Close Combat II","Heft"]},
{name:"Charge Regulation",role:"Charges / Crit",supports:["Vitality II","Clarity II","Precision II"]},
{name:"Spirit Vessel",role:"Passif / utilitaire",supports:["Meat Shield II","Wing Blast","Romira's Requital","Amanamu's Tithe"]},
{name:"Elemental Conflux",role:"Optionnel",supports:["Elemental Focus II","Innervate"]}
],
skillDamageSnapshot:{note:"Valeurs de référence visuelle ; à recalculer après verrouillage crit/Mana.",entries:[["Hollow Form / Whirling Assault",52000,86000],["Shattering Palm (explosion)",38000,64000],["Charged Staff",24000,41000],["Tempest Bell (explosion)",18000,32000],["Hollow Resonance",12000,21000],["Hollow Focus",10000,17000]]},
priorities:[{id:1,title:"Chance de critique réelle",status:"ACTIVE",note:"Utiliser les deux suffixes libérés, comparer Duality 15% et les Jewel Sockets sans toucher à l'arbre."},{id:2,title:"Sustain Mana",status:"OPEN",note:"Tester Hollow Form / Whirling Assault prolongé avec +3 Mêlée et Attack Speed final."},{id:3,title:"Budget Spirit",status:"OPEN",note:"Convalescence supprimée ; auditer Vitality II et Elemental Conflux."},{id:4,title:"Gros hits physiques",status:"OPEN",note:"Améliorer sans casser ES/Evasion/contrôle."},{id:5,title:"Supports secondaires",status:"OPEN",note:"Auditer Pinpoint Critical, Overabundance II, Rage III et Innervate boss."},{id:6,title:"Clear final",status:"LATER",note:"Ne pas sacrifier bossing/survie si Shattering Palm clear déjà instantanément."}]
};