window.HOLLOW_DOMINION_DATA={
meta:{name:"HOLLOW DOMINION",author:"Nejib",gameVersion:"0.5.2",className:"Monk",ascendancy:"Martial Artist",passiveTree:"Default 120 + 8",referenceImage:"ChatGPT Image 9 sept. 2026, 05_47_28(1).png",stateVersion:"live-1.0",updated:"2026-09-09",note:"Convalescence est définitivement exclue. Les suffixes libérés du Masque souriant et de l'Amulette solaire restent vierges pour le moment."},
rules:{endgameElementalPenalty:-60,endgameChaosPenalty:0,resistanceCap:75,campaignElementalBonus:{fire:10,cold:10,lightning:10,chaos:0},treeResistanceBonus:{fire:5,cold:5,lightning:5,chaos:5},ingenuityLeftRingBonusPct:30,ingenuityRightRingBonusPct:30},
referenceSnapshot:{life:1642,mana:1218,energyShield:6487,evasion:18245,deflection:8020,movementSpeedPct:37,strength:95,dexterity:195,intelligence:95,critChancePct:62,critDamageBonusPct:275,attackSpeed:2.48,manaRegenPerSecond:312,spiritTotal:245,spiritReserved:207,resistancesDisplayed:{fire:75,cold:75,lightning:75,chaos:75}},
workingCharacter:{level:100,life:1642,mana:1218,energyShield:6487,evasion:18245,deflection:8020,movementSpeedPct:37,strength:95,dexterity:195,intelligence:95,crit:{weaponBasePct:10,increasedPctFromTree:-10,increasedPctFromGear:0,increasedPctFromJewels:0,morePctPowerChargeCondition:26,morePctBlindsideCondition:15},critDamageBonusPct:275,attackSpeed:2.48,manaRegenPerSecond:312,spiritTotal:245,spiritReserved:177},
gear:{
helmet:{slot:"Casque",name:"Masque souriant",rarity:"Rare BiS — travail",prefixes:[{label:"+120 maximum ES",value:120,stat:"maxES"},{label:"+140% Évasion et ES",value:140,stat:"localEvasionESPct"},{label:"+90 Mana maximal",value:90,stat:"maxMana"}],suffixes:[{label:"+45 Dextérité",value:45,stat:"dexterity"},{label:"+40% Résistance feu",value:40,stat:"resFire"},{label:"Suffixe libre — à optimiser",value:0,stat:null,status:"free"}]},
gloves:{slot:"Gants",name:"Caresse de Lochton",rarity:"Unique / Way of the Stonefist",unique:["Interaction Stonefist obligatoire","+4 Evasion et +2 ES par niveau — à contrôler en jeu","Cannot Leech Mana après transformation","Génération/partage de charges"]},
weapon:{slot:"Arme",name:"Duality",rarity:"Unique — Runemastered Warding Quarterstaff",unique:["+50 maximum Runic Ward","+300% increased Physical Damage","+30% Critical Damage Bonus","+22% increased Attack Speed","Variante 10% crit actuelle ; variante 15% à comparer"]},
chest:{slot:"Armure",name:"Veste racée",rarity:"Rare BiS — travail",prefixes:[{label:"+180 maximum ES",value:180,stat:"maxES"},{label:"+160% Évasion et ES",value:160,stat:"localEvasionESPct"},{label:"+61 Spirit",value:61,stat:"spirit"}],suffixes:[{label:"+40% Résistance feu",value:40,stat:"resFire"},{label:"+40% Résistance froid",value:40,stat:"resCold"},{label:"+41% Résistance foudre",value:41,stat:"resLightning"}]},
belt:{slot:"Ceinture",name:"Ingéniosité",rarity:"Unique",unique:["Objectif BiS : +30% bonus bague gauche","Objectif BiS : +30% bonus bague droite","1–3 emplacements de Charme"]},
boots:{slot:"Bottes",name:"Chaussures à dague",rarity:"Rare BiS — travail",prefixes:[{label:"+95 maximum ES",value:95,stat:"maxES"},{label:"+140% Évasion et ES",value:140,stat:"localEvasionESPct"},{label:"+35% Vitesse de déplacement",value:35,stat:"moveSpeedPct"}],suffixes:[{label:"+40% Résistance feu",value:40,stat:"resFire"},{label:"+40% Résistance froid",value:40,stat:"resCold"},{label:"+40% Résistance foudre",value:40,stat:"resLightning"}]},
amulet:{slot:"Amulette",name:"Amulette solaire",rarity:"Rare BiS — travail",implicits:[{label:"+15 Spirit",value:15,stat:"spirit"}],prefixes:[{label:"+50 Spirit",value:50,stat:"spirit"},{label:"+74 Mana maximal",value:74,stat:"maxMana"},{label:"+40 maximum ES",value:40,stat:"maxES"}],suffixes:[{label:"+3 niveau de toutes les Aptitudes de Mêlée",value:3,stat:"meleeSkillLevels"},{label:"+40% Résistance froid",value:40,stat:"resCold"},{label:"Suffixe libre — à optimiser",value:0,stat:null,status:"free"}]},
ringAmethyst:{slot:"Bague gauche",name:"Bague d'Améthyste",rarity:"Rare BiS — travail",ingenuitySide:"left",implicits:[{label:"+13% Résistance chaos",value:13,stat:"resChaos",ingenuity:true}],prefixes:[{label:"+85 maximum ES",value:85,stat:"maxES",ingenuity:true},{label:"+35 Mana maximal",value:35,stat:"maxMana",ingenuity:true},{label:"+15 Dextérité",value:15,stat:"dexterity",ingenuity:true}],suffixes:[{label:"+45% Dégâts de froid",value:45,stat:"coldDamagePct",ingenuity:true},{label:"+35% Bonus de Dégâts critiques",value:35,stat:"critDamageBonusPct",ingenuity:true},{label:"+20% Résistance chaos",value:20,stat:"resChaos",ingenuity:true}]},
ringTopaz:{slot:"Bague droite",name:"Bague de Topaze",rarity:"Rare BiS — travail",ingenuitySide:"right",implicits:[{label:"+30% Résistance foudre",value:30,stat:"resLightning",ingenuity:true}],prefixes:[{label:"+90 maximum ES",value:90,stat:"maxES",ingenuity:true},{label:"+33 Force",value:33,stat:"strength",ingenuity:true},{label:"+30% Vitesse d'attaque",value:30,stat:"attackSpeedPct",ingenuity:true,status:"audit"}],suffixes:[{label:"+21% Résistance chaos",value:21,stat:"resChaos",ingenuity:true},{label:"Suffixe à définir",value:0,stat:null,status:"open"},{label:"Suffixe à définir",value:0,stat:null,status:"open"}]}
},
skills:[
{name:"Hollow Form → Whirling Assault",role:"Main DPS boss",supports:["Heavy Swing","Heightened Charges","Blindside","Vorana's Siege"]},
{name:"Shattering Palm",role:"Clear / Freeze",supports:["Ancestral Call II","Rapid Attacks II","Magnified Area II","Elemental Armament II","Rising Tempest"]},
{name:"Charged Staff",role:"Lightning / Shock / Blind",supports:["Blind II","Perpetual Charge","Prolonged Duration II","Elemental Armament II","Innervate"]},
{name:"Tempest Bell",role:"Burst / Elemental",supports:["Heavy Swing","Close Combat II","Ancestral Call II","Overabundance II","Rage III"]},
{name:"Hollow Resonance",role:"Stun",supports:["Stun III","Cooldown Recovery II","Close Combat II","Magnified Area II","Pinpoint Critical"]},
{name:"Hollow Focus",role:"Heavy Stun",supports:["Cooldown Recovery II","Overabundance II","Magnified Area II","Close Combat II","Heft"]},
{name:"Charge Regulation",role:"Charges / Crit",supports:["Vitality II","Clarity II","Precision II"]},
{name:"Spirit Vessel",role:"Passif / utilitaire",supports:["Meat Shield II","Wing Blast","Romira's Requital","Amanamu's Tithe"]},
{name:"Elemental Conflux",role:"Optionnel",supports:["Elemental Focus II","Innervate"]}
],
skillDamageSnapshot:{note:"Valeurs de référence visuelle ; à recalculer après verrouillage crit/Mana.",entries:[["Hollow Form / Whirling Assault",52000,86000],["Shattering Palm (explosion)",38000,64000],["Charged Staff",24000,41000],["Tempest Bell (explosion)",18000,32000],["Hollow Resonance",12000,21000],["Hollow Focus",10000,17000]]},
priorities:[{id:1,title:"Chance de critique réelle",status:"ACTIVE",note:"Utiliser les deux suffixes libérés, comparer Duality 15% et les Jewel Sockets sans toucher à l'arbre."},{id:2,title:"Sustain Mana",status:"OPEN",note:"Tester Hollow Form / Whirling Assault prolongé avec +3 Mêlée et Attack Speed final."},{id:3,title:"Budget Spirit",status:"OPEN",note:"Convalescence supprimée ; auditer Vitality II et Elemental Conflux."},{id:4,title:"Gros hits physiques",status:"OPEN",note:"Améliorer sans casser ES/Evasion/contrôle."},{id:5,title:"Supports secondaires",status:"OPEN",note:"Auditer Pinpoint Critical, Overabundance II, Rage III et Innervate boss."},{id:6,title:"Clear final",status:"LATER",note:"Ne pas sacrifier bossing/survie si Shattering Palm clear déjà instantanément."}]
};