window.HOLLOW_DOMINION_DATA={
meta:{name:"HOLLOW DOMINION",author:"Nejib",gameVersion:"0.5.2",className:"Monk",ascendancy:"Martial Artist",passiveTree:"Default 120 + 8",referenceImage:"ChatGPT Image 9 sept. 2026, 05_47_28(1).png",stateVersion:"live-1.8-wind-dancer-supports",updated:"2026-09-09",note:"Stuff et compétences/supports intégrés au vrai live build. Spirit Vessel a été retiré car l'aptitude est octroyée par Forgotten Warden, incompatible avec notre Veste racée. Danseur du vent est désormais actif à sa place. Vitalité II est définitivement retirée de Régulation des charges. Pour cette phase, l'arbre et les bonus permanents de campagne sont des constantes verrouillées ; seule la couche équipement est modifiable dans l'interface et pilote les statistiques."},
rules:{endgameElementalPenalty:-60,endgameChaosPenalty:0,resistanceCap:75,ingenuityRounding:"floor-per-mod",qualityLocalDefenceMorePerPct:1},
campaignFixed:{
attributes:{strength:5,dexterity:5,intelligence:5},flatLife:20,maxLifePct:5,maxManaPct:5,spirit:100,manaRegenPct:25,kaomDefencesPct:30,resistances:{fire:15,cold:15,lightning:15,chaos:0},ancientVowsCharmChargesGainedPct:30,manaRecoveryFromFlasksPct:30,
note:"Choix verrouillés : Ancient Vows +30% Charm Charges gained ; Venom Crypts +25% Mana Regeneration Rate ; +5 STR/DEX/INT ; Kaom's Lesson +30% Armour/Evasion/ES ; Goddess of Justice +30% Mana Recovery from Flasks ; Tabana +5% all Elemental Resistances. Les résistances incluent aussi les +10% fixes Feu/Froid/Foudre de campagne."
},
gear:{
helmet:{slot:"Casque",name:"Masque souriant",rarity:"Rare BiS — travail",quality:20,baseStats:{evasion:187,energyShield:57},prefixes:[{label:"+120 maximum ES",value:120,stat:"localFlatES"},{label:"+140% Évasion et ES",value:140,stat:"localEvasionESPct"},{label:"+90 Mana maximal",value:90,stat:"maxMana"}],suffixes:[{label:"+45 Dextérité",value:45,stat:"dexterity"},{label:"+40% Résistance feu",value:40,stat:"resFire"},{label:"Suffixe libre — réservé pour le critique",value:0,stat:null,status:"free",editableStat:true}]},
gloves:{slot:"Gants",name:"Caresse de Lochton → Poings de pierre",rarity:"Unique / Way of the Stonefist",quality:20,transformed:{evasionPerLevel:4,energyShieldPerLevel:2,attackSpeedPct:20,cannotLeechMana:true},unique:["Base transformée par Way of the Stonefist","+4 Évasion et +2 ES par niveau avant qualité","20% increased Attack Speed — roll de travail maximal, éditable","Cannot Leech Mana après transformation","Génération / partage de charges"]},
weapon:{slot:"Arme",name:"Duality",rarity:"Unique — Runemastered Warding Quarterstaff",weaponStats:{physicalMin:85,physicalMax:141,baseCritPct:10,baseAPS:1.40,localPhysicalIncreasedPct:300,localAttackSpeedPct:22,criticalDamageBonusFlatPct:30,runicWard:50},unique:["+50 maximum Runic Ward","+300% increased Physical Damage","+30% Critical Damage Bonus","+22% increased Attack Speed local","Base crit 10% actuelle ; variante 15% à comparer"]},
chest:{slot:"Armure",name:"Veste racée",rarity:"Rare BiS — travail",quality:20,baseStats:{evasion:285,energyShield:87},baseMovementSpeedPct:-3,prefixes:[{label:"+180 maximum ES",value:180,stat:"localFlatES"},{label:"+160% Évasion et ES",value:160,stat:"localEvasionESPct"},{label:"+61 Spirit",value:61,stat:"spirit"}],suffixes:[{label:"+40% Résistance feu",value:40,stat:"resFire"},{label:"+40% Résistance froid",value:40,stat:"resCold"},{label:"+41% Résistance foudre",value:41,stat:"resLightning"}]},
belt:{slot:"Ceinture",name:"Ingéniosité",rarity:"Unique",ringBonusLeftPct:30,ringBonusRightPct:30,unique:["Objectif BiS : +30% bonus bague gauche","Objectif BiS : +30% bonus bague droite","1–3 emplacements de Charme"]},
boots:{slot:"Bottes",name:"Chaussures à dague",rarity:"Rare BiS — travail",quality:20,baseStats:{evasion:140,energyShield:43},prefixes:[{label:"+95 maximum ES",value:95,stat:"localFlatES"},{label:"+140% Évasion et ES",value:140,stat:"localEvasionESPct"},{label:"+35% Vitesse de déplacement",value:35,stat:"moveSpeedPct"}],suffixes:[{label:"+40% Résistance feu",value:40,stat:"resFire"},{label:"+40% Résistance froid",value:40,stat:"resCold"},{label:"+40% Résistance foudre",value:40,stat:"resLightning"}]},
amulet:{slot:"Amulette",name:"Amulette solaire",rarity:"Rare BiS — travail",implicits:[{label:"+15 Spirit",value:15,stat:"spirit"}],prefixes:[{label:"+50 Spirit",value:50,stat:"spirit"},{label:"+74 Mana maximal",value:74,stat:"maxMana"},{label:"+40 maximum ES",value:40,stat:"maxES"}],suffixes:[{label:"+3 niveau de toutes les Aptitudes de Mêlée",value:3,stat:"meleeSkillLevels"},{label:"+40% Résistance froid",value:40,stat:"resCold"},{label:"Suffixe libre — réservé pour le critique",value:0,stat:null,status:"free",editableStat:true}]},
ringAmethyst:{slot:"Bague gauche",name:"Bague d'Améthyste",rarity:"Rare BiS — travail",ingenuitySide:"left",implicits:[{label:"+13% Résistance chaos",value:13,stat:"resChaos",ingenuity:true}],prefixes:[{label:"+85 maximum ES",value:85,stat:"maxES",ingenuity:true},{label:"+35 Mana maximal",value:35,stat:"maxMana",ingenuity:true},{label:"+15 Dextérité",value:15,stat:"dexterity",ingenuity:true}],suffixes:[{label:"+45% Dégâts de froid",value:45,stat:"coldDamagePct",ingenuity:true},{label:"+35% Bonus de Dégâts critiques",value:35,stat:"critDamageBonusFlatPct",ingenuity:true},{label:"+20% Résistance chaos",value:20,stat:"resChaos",ingenuity:true}]},
ringTopaz:{slot:"Bague droite",name:"Bague de Topaze",rarity:"Rare BiS — travail",ingenuitySide:"right",implicits:[{label:"+30% Résistance foudre",value:30,stat:"resLightning",ingenuity:true}],prefixes:[{label:"+90 maximum ES",value:90,stat:"maxES",ingenuity:true},{label:"+33 Force",value:33,stat:"strength",ingenuity:true},{label:"+30% Vitesse d'attaque",value:30,stat:"attackSpeedPct",ingenuity:true,status:"audit",active:false}],suffixes:[{label:"Suffixe offensif existant — valeur à auditer",value:0,stat:null,status:"audit",editableStat:true},{label:"+21% Résistance chaos",value:21,stat:"resChaos",ingenuity:true},{label:"Suffixe offensif existant — valeur à auditer",value:0,stat:null,status:"audit",editableStat:true}]}
},
skills:[
{name:"Hollow Form → Whirling Assault",role:"Main DPS boss",active:true,supports:["Heavy Swing","Heightened Charges","Blindside","Vorana's Siege"]},
{name:"Shattering Palm",role:"Clear / Freeze / Overkill",active:true,supports:["Ancestral Call II","Rapid Attacks II","Magnified Area II","Elemental Armament II","Rising Tempest"]},
{name:"Charged Staff",role:"Lightning / Shock / Blind / contrôle boss",active:true,supports:["Blind II","Perpetual Charge","Prolonged Duration II","Elemental Armament II","Innervate"]},
{name:"Tempest Bell",role:"Burst élémentaire",active:true,supports:["Heavy Swing","Close Combat II","Ancestral Call II","Overabundance II","Rage III"]},
{name:"Hollow Resonance",role:"Stun",active:true,supports:["Stun III","Cooldown Recovery II","Close Combat II","Magnified Area II","Pinpoint Critical"]},
{name:"Hollow Focus",role:"Heavy Stun",active:true,supports:["Cooldown Recovery II","Overabundance II","Magnified Area II","Close Combat II","Heft"]},
{name:"Charge Regulation",role:"Charges / utilitaire",active:true,spiritReservation:70,reservationBreakdown:"30 base + Clarity II 20 + Precision II 20",supports:["Clarity II","Precision II"]},
{name:"Danseur du vent",role:"Défense / Évasion / Repoussement / contrôle",active:true,spiritReservation:30,reservationBreakdown:"30 Esprit",supports:["Maim","Pin I","Lockdown"],optionalSupports:["Blind II","Her Declaration"]},
{name:"Elemental Conflux",role:"Optionnel",active:false,spiritReservation:60,supports:["Elemental Focus II","Innervate"]}
],
priorities:[{id:1,title:"Chance de critique réelle",status:"ACTIVE",note:"Utiliser les deux suffixes libres, comparer Duality 15% et les Jewel Sockets sans toucher à l'arbre."},{id:2,title:"Sustain Mana",status:"OPEN",note:"Tester Hollow Form / Whirling Assault prolongé avec +3 Mêlée et Attack Speed final."},{id:3,title:"Budget Spirit",status:"OPEN",note:"Spirit Vessel et Vitalité II supprimés ; Danseur du vent actif pour 30 Esprit. Réservation actuelle : 100 / 226, soit 126 Esprit libres. Elemental Conflux reste optionnel."},{id:4,title:"Gros hits physiques",status:"OPEN",note:"Améliorer sans casser ES/Evasion/contrôle."},{id:5,title:"Supports secondaires",status:"OPEN",note:"Danseur du vent : Maim + Pin I + Lockdown verrouillés ; Blind II et Her Declaration restent facultatifs. Auditer aussi Pinpoint Critical, Overabundance II, Rage III et Innervate boss."},{id:6,title:"Clear final",status:"LATER",note:"Ne pas sacrifier bossing/survie si Shattering Palm clear déjà instantanément."}]
};