(function(){
const RES_MAP={resFire:'fire',resCold:'cold',resLightning:'lightning',resChaos:'chaos'};
const num=v=>Number.isFinite(Number(v))?Number(v):0;
const allAffixes=i=>[...(i.implicits||[]),...(i.prefixes||[]),...(i.suffixes||[])];
function ringMultiplier(item,data){if(!item.ingenuitySide)return 1;const b=data.gear.belt||{};const pct=item.ingenuitySide==='left'?num(b.ringBonusLeftPct):num(b.ringBonusRightPct);return 1+pct/100;}
function effectiveAffixValue(a,item,data){if(a.active===false)return 0;let v=num(a.value);if(a.ingenuity){v*=ringMultiplier(item,data);if(data.rules.ingenuityRounding==='floor-per-mod')v=Math.floor(v+1e-9);}return v;}
function sumGearStat(data,stat){let total=0;Object.values(data.gear).forEach(item=>allAffixes(item).forEach(a=>{if(a.stat===stat)total+=effectiveAffixValue(a,item,data);}));return total;}
function localDefence(item,data,type){if(!item.defenceBase)return 0;const base=num(item.defenceBase[type]);const flatStat=type==='energyShield'?'localFlatES':'localFlatEvasion';let flat=0,inc=0;allAffixes(item).forEach(a=>{if(a.active===false)return;if(a.stat===flatStat)flat+=num(a.value);if(a.stat==='localEvasionESPct')inc+=num(a.value);if(type==='energyShield'&&a.stat==='localESPct')inc+=num(a.value);if(type==='evasion'&&a.stat==='localEvasionPct')inc+=num(a.value);});const qualityMore=1+num(item.quality)*num(data.rules.qualityLocalDefenceMorePerPct)/100;return Math.floor((base+flat)*(1+inc/100)*qualityMore+1e-9);}
function calcItemDefences(item,data){return{evasion:localDefence(item,data,'evasion'),energyShield:localDefence(item,data,'energyShield')};}
function calcAttributes(data){const c=data.fixedSources.character,t=data.fixedSources.tree,cp=data.fixedSources.campaign;const fixed=t.fixedAttributes||{},flex=t.flexibleAttributes||{},camp=cp.attributes||{};return{strength:Math.floor(num(c.baseStrength)+num(fixed.strength)+num(flex.strength)+num(camp.strength)+sumGearStat(data,'strength')),dexterity:Math.floor(num(c.baseDexterity)+num(fixed.dexterity)+num(flex.dexterity)+num(camp.dexterity)+sumGearStat(data,'dexterity')),intelligence:Math.floor(num(c.baseIntelligence)+num(fixed.intelligence)+num(flex.intelligence)+num(camp.intelligence)+sumGearStat(data,'intelligence'))};}
function calcLifeMana(data,attributes){const c=data.fixedSources.character,cp=data.fixedSources.campaign;const level=num(c.level);const lifeBase=num(c.baseLife)+num(c.lifePerLevel)*level+2*num(attributes.strength)+num(cp.flatLife)+sumGearStat(data,'maxLife');const manaBase=num(c.baseMana)+num(c.manaPerLevel)*level+2*num(attributes.intelligence)+sumGearStat(data,'maxMana');return{life:Math.floor(lifeBase*(1+num(cp.maxLifePct)/100)+1e-9),mana:Math.floor(manaBase*(1+num(cp.maxManaPct)/100)+1e-9)};}
function calcDefences(data){const t=data.fixedSources.tree,cp=data.fixedSources.campaign,c=data.fixedSources.character;let itemEvasion=0,itemES=0;Object.values(data.gear).forEach(item=>{const d=calcItemDefences(item,data);itemEvasion+=d.evasion;itemES+=d.energyShield;});const chestEvasion=calcItemDefences(data.gear.chest||{},data).evasion;const spectralWard=Math.floor(chestEvasion/Math.max(1,num(t.spectralWardBodyEvasionDivisor)));const globalFlatES=sumGearStat(data,'maxES')+spectralWard;const incES=num(t.increasedEnergyShieldPct)+num(cp.kaomDefencesPct);const incEvasion=num(t.increasedEvasionPct)+num(cp.kaomDefencesPct);const baseEvasion=itemEvasion+num(c.baseEvasion);const energyShield=Math.floor((itemES+globalFlatES)*(1+incES/100)+1e-9);const evasion=Math.floor(baseEvasion*(1+incEvasion/100)+1e-9);const deflection=Math.floor(evasion*num(t.evasionAsDeflectionPct)/100+1e-9);const evasionShimmering=Math.floor(baseEvasion*(1+(incEvasion+num(t.evasionIfNotHitRecentlyPct))/100)+1e-9);const deflectionShimmering=Math.floor(evasionShimmering*num(t.evasionAsDeflectionPct)/100+1e-9);return{itemEvasion,itemEnergyShield:itemES,spectralWard,globalFlatES,incES,incEvasion,energyShield,evasion,deflection,evasionShimmering,deflectionShimmering};}
function calcResistances(data){const t=data.fixedSources.tree,cp=data.fixedSources.campaign;const raw={fire:num(t.resistances?.fire)+num(cp.resistances?.fire),cold:num(t.resistances?.cold)+num(cp.resistances?.cold),lightning:num(t.resistances?.lightning)+num(cp.resistances?.lightning),chaos:num(t.resistances?.chaos)+num(cp.resistances?.chaos)};Object.values(data.gear).forEach(item=>allAffixes(item).forEach(a=>{const k=RES_MAP[a.stat];if(k)raw[k]+=effectiveAffixValue(a,item,data);}));const afterPenalty={fire:raw.fire+num(data.rules.endgameElementalPenalty),cold:raw.cold+num(data.rules.endgameElementalPenalty),lightning:raw.lightning+num(data.rules.endgameElementalPenalty),chaos:raw.chaos+num(data.rules.endgameChaosPenalty)};const capped={};Object.keys(afterPenalty).forEach(k=>capped[k]=Math.min(num(data.rules.resistanceCap),afterPenalty[k]));return{raw,afterPenalty,capped};}
function calcCrit(data){const t=data.fixedSources.tree,c=data.fixedSources.character,w=data.gear.weapon||{};const increased=num(t.critChanceIncreasedPct)+sumGearStat(data,'critChancePct');const permanent=num(w.baseCritPct)*(1+increased/100);const vsDazed=num(w.baseCritPct)*(1+(increased+num(t.critChanceVsDazedIncreasedPct))/100);const critDamageBonus=num(c.baseCritDamageBonusPct)+num(t.critDamageBonusPct)+num(w.critDamageBonusPct)+sumGearStat(data,'critDamageBonusPct');return{baseWeapon:num(w.baseCritPct),increased,permanent,vsDazed,critDamageBonus,critDamageAfterPowerCharge:critDamageBonus+num(t.critDamageBonusAfterPowerChargePct)};}
function calcSpirit(data){const total=num(data.fixedSources.campaign.spirit)+sumGearStat(data,'spirit'),reserved=num(data.fixedSources.skills.spiritReserved);return{total,reserved,free:total-reserved};}
function calcMovement(data){const t=data.fixedSources.tree;let gearMove=sumGearStat(data,'moveSpeedPct');Object.values(data.gear).forEach(i=>gearMove+=num(i.baseMovementSpeedPct));const permanent=gearMove+num(t.movementSpeedPct);return{permanent,whileEnergyShield:permanent+num(t.movementSpeedWhileEnergyShieldPct)};}
function calcManaRegen(data,mana){const c=data.fixedSources.character,t=data.fixedSources.tree,cp=data.fixedSources.campaign,s=data.fixedSources.skills;const base=num(mana)*num(c.baseManaRegenPctPerSecond)/100;const permanentInc=num(t.manaRegenPct)+num(cp.manaRegenPct);const withClarityInc=permanentInc+num(s.clarityManaRegenPct);const withShockInc=withClarityInc+num(s.recentShockManaRegenPct);return{base,permanent:base*(1+permanentInc/100),withClarity:base*(1+withClarityInc/100),withClarityAndRecentShock:base*(1+withShockInc/100),permanentInc,withClarityInc,withShockInc};}
function calcAttackSpeed(data){const t=data.fixedSources.tree,w=data.gear.weapon||{},g=data.gear.gloves||{};const weaponAPS=num(w.baseAttackSpeed)*(1+num(w.localAttackSpeedPct)/100);const gearGlobal=sumGearStat(data,'attackSpeedPct');const treeGlobal=num(t.skillSpeedPct)+num(t.attackCastSpeedPct)+num(t.quarterstaffAttackSpeedPct);const minInc=treeGlobal+gearGlobal+num(g.attackSpeedPctMin),maxInc=treeGlobal+gearGlobal+num(g.attackSpeedPctMax);return{weaponAPS,treeGlobal,gearGlobal,min:weaponAPS*(1+minInc/100),max:weaponAPS*(1+maxInc/100),minInc,maxInc};}
function calcAll(data){const attributes=calcAttributes(data),resources=calcLifeMana(data,attributes),defences=calcDefences(data),resistances=calcResistances(data),crit=calcCrit(data),spirit=calcSpirit(data),movement=calcMovement(data),manaRegen=calcManaRegen(data,resources.mana),attackSpeed=calcAttackSpeed(data);return{attributes,resources,defences,resistances,crit,spirit,movement,manaRegen,attackSpeed,runicWard:num(data.gear.weapon?.runicWard)};}
window.HD_CALC={effectiveAffixValue,calcItemDefences,calcAttributes,calcLifeMana,calcDefences,calcResistances,calcCrit,calcSpirit,calcMovement,calcManaRegen,calcAttackSpeed,calcAll};
})();